type HR = {
  "Moderate Risk": number;
  Healthy: number;
  "Caution Needed": number;
  Unknown: number;
  "High Risk": number;
};
type M = {
  Mature: number;
  Unknown: number;
  Legacy: number;
  Experimental: number;
};

type Breakdown = {
  health_risk: { direct: HR; indirect: HR };
  maturity: { direct: M; indirect: M };
};
export const breakdown: Breakdown = {
  health_risk: {
    direct: {
      "Moderate Risk": 45,
      Healthy: 24,
      "Caution Needed": 72,
      Unknown: 8,
      "High Risk": 4,
    },
    indirect: {
      "Caution Needed": 19,
      "Moderate Risk": 15,
      Healthy: 8,
      Unknown: 4,
      "High Risk": 1,
    },
  },
  maturity: {
    direct: {
      Mature: 123,
      Unknown: 14,
      Legacy: 21,
      Experimental: 1,
    },
    indirect: {
      Mature: 37,
      Legacy: 6,
      Unknown: 5,
      Experimental: 0,
    },
  },
};

export const projectData = {
  name: "Repos",
  riskBreakdown: {
    direct: {
      healthy: 12,
      moderate: 5,
      high: 2,
    },
    indirect: {
      healthy: 16,
      moderate: 7,
      high: 3,
    },
  },
  maturityBreakdown: {
    direct: {
      mature: 10,
      experimental: 6,
      legacy: 3,
    },
    indirect: {
      mature: 15,
      experimental: 9,
      legacy: 2,
    },
  },
  insurance: {
    core: {
      cost: 8000,
      coverage: 500000,
      items: [
        "Dependency failure incidents",
        "Emergency replacements",
        "Security incident response",
        "Business interruption",
      ],
    },
    legal: {
      cost: 3222,
      coverage: 1000000,
      items: [
        "License compliance issues",
        "Legal defense costs",
        "Indemnification",
      ],
    },
    support: {
      items: [
        { service: "Emergency Support", rate: "250/hour" },
        { service: "Migration Assistance", rate: "200/hour" },
        { service: "Packaging Support", rate: "150/hour" },
      ],
    },
  },
};

export const affectedPackages: { [key: string]: string[] } = {
  NO_LICENSE: [
    "alabaster",
    "imagesize",
    "pyasn1",
    "drf-yasg",
    "Sphinx",
    "matplotlib",
  ],
  NO_PROJECT_NAME: [
    "pyasn1-modules",
    "google-auth-httplib2",
    "jedi",
    "pure-eval",
    "proto-plus",
    "django-extensions",
    "h11",
    "Babel",
    "simplejson",
    "realtime",
    "pipreqs",
    "debugpy",
    "identify",
    "dj-database-url",
    "cachetools",
    "asttokens",
    "imagesize",
    "pandocfilters",
    "google-cloud-secret-manager",
    "anyio",
    "requests",
    "gotrue",
    "google-crc32c",
    "lxml",
    "requests-oauthlib",
    "gdoctableapppy",
    "postgrest",
    "openapi-codec",
    "google-cloud-storage",
    "itypes",
    "google-api-core",
    "wcwidth",
    "stack-data",
    "charset-normalizer",
    "djangorestframework",
    "PyYAML",
    "isort",
    "google-cloud",
    "certifi",
    "prompt-toolkit",
    "googleapis-common-protos",
    "parso",
    "django-docs",
    "html5lib",
    "six",
    "snowballstemmer",
    "grpc-google-iam-v1",
    "decorator",
    "python-dotenv",
    "PyJWT",
    "google-cloud-core",
    "executing",
    "tzdata",
    "inflection",
    "pickleshare",
    "pre-commit",
    "coreapi",
    "rsa",
    "mypy-extensions",
    "supafunc",
    "pyasn1",
    "storage3",
    "distlib",
    "google-auth",
    "coreschema",
    "google-resumable-media",
    "psutil",
    "deprecation",
    "psycopg2-binary",
    "grpcio",
    "nodeenv",
    "python-dateutil",
    "drf-yasg",
    "tornado",
    "drf-spectacular",
    "django-rest-swagger",
    "cfgv",
    "asgiref",
    "google-auth-oauthlib",
    "psycopg2",
    "distro",
    "oauthlib",
    "google-api-python-client",
    "StrEnum",
    "django-crontab",
    "httplib2",
    "nest-asyncio",
    "regex",
  ],
  LICENSE_MODIFIED: [
    "pyasn1-modules",
    "psutil",
    "jedi",
    "Pygments",
    "decorator",
    "python-dotenv",
    "h11",
    "openapi-codec",
    "matplotlib-inline",
    "nodeenv",
    "Babel",
    "pandas",
    "django-cors-headers",
    "simplejson",
    "drf-spectacular",
    "django-rest-swagger",
    "debugpy",
    "wcwidth",
    "idna",
    "pydantic",
    "mypy-extensions",
    "djangorestframework",
    "scipy",
    "ipykernel",
    "django-crontab",
    "traitlets",
    "nest-asyncio",
    "pyzmq",
  ],
  REPO_NOT_FOUND: [
    "uritemplate",
    "grpcio-status",
    "plotly",
    "docutils",
    "beautifulsoup4",
    "protobuf",
  ],
  Unknown: [
    "grpcio",
    "packaging",
    "python-dateutil",
    "sniffio",
    "distlib",
    "tzdata",
    "certifi",
    "psycopg2",
    "Markdown",
    "filelock",
    "pillow",
    "rsa",
    "psycopg2-binary",
    "parso",
  ],
  ONE_AUTHORS_THIS_YEAR: [
    "pathspec",
    "pyasn1-modules",
    "comm",
    "colorama",
    "tzdata",
    "jsonschema-specifications",
    "cfgv",
    "nest-asyncio",
    "grpc-google-iam-v1",
    "pickleshare",
    "sphinxcontrib-applehelp",
    "sphinxcontrib-devhelp",
    "googleapis-common-protos",
    "regex",
    "h11",
    "parso",
  ],
  NO_AUTHORS_THIS_YEAR: [
    "coreschema",
    "deprecation",
    "gdoctableapppy",
    "sphinxcontrib-htmlhelp",
    "decorator",
    "openapi-codec",
    "drf-yasg",
    "sphinxcontrib-qthelp",
    "inflection",
    "itypes",
    "coreapi",
    "sphinxcontrib-serializinghtml",
    "django-rest-swagger",
    "charset-normalizer",
    "mypy-extensions",
    "PyYAML",
    "StrEnum",
    "imagesize",
    "django-crontab",
    "httplib2",
    "django-docs",
  ],
  PACKGE_SKEW_NOT_UPDATED: [
    "html5lib",
    "django-crontab",
    "colorama",
    "click",
    "google-cloud",
    "rsa",
    "six",
    "deprecation",
    "snowballstemmer",
    "inflection",
    "pickleshare",
    "oauthlib",
    "decorator",
    "h11",
  ],
  LAST_COMMIT_5_YEARS: [
    "django-rest-swagger",
    "django-crontab",
    "coreschema",
    "coreapi",
    "openapi-codec",
  ],
  LICENSE_CHECKOUT_ERROR: [
    "referencing",
    "termcolor",
    "coreschema",
    "jsonschema",
    "jsonschema-specifications",
    "sphinxcontrib-qthelp",
    "snowballstemmer",
    "gdoctableapppy",
    "sphinxcontrib-htmlhelp",
    "sphinxcontrib-devhelp",
    "tqdm",
    "scikit-learn",
    "sphinxcontrib-serializinghtml",
    "sphinxcontrib-applehelp",
  ],
  LESS_PERMISSIVE_LICENSE: ["pathspec"],
  INSECURE_CONNECTION: ["pytz", "sphinxcontrib-jsmath"],
  FEW_MAX_MONTHLY_AUTHORS: ["sphinxcontrib-devhelp"],
  PACKGE_SKEW_NOT_RELEASED: [
    "sphinxcontrib-htmlhelp",
    "sphinxcontrib-serializinghtml",
    "sphinxcontrib-qthelp",
  ],
};
