name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"
      - name: Install dependencies
        run: |
          npm ci --force
      - name: Lint
        run: |
          npm run lint
      # TODO: add tests
      # - name: Test
      #   run: |
      #     npm run test
      - name: Build
        run: |
          npm run build
