name: PR Annotations

on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      pull-requests: read

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"
      - name: Install dependencies
        run: |
          npm ci --force
      - name: Lint
        run: |
          npm run lint:report
        continue-on-error: true
      - name: Annotate Code
        uses: DerLev/eslint-annotations@v1
        with:
          eslint-report: eslint_report.json
